/*
 * Контент сайта. Чтобы добавить работу, скопируйте один объект в массиве artworks.
 * Подробная инструкция находится в README.md.
 */
window.SITE_CONTENT = {
  translations: {
    ru: {
      skip: "К содержанию",
      menu: "Меню",
      navLabel: "Основная навигация",
      languageLabel: "Выбор языка",
      filterLabel: "Фильтр работ",
      close: "Закрыть",
      navAbout: "О художнике",
      navWorks: "Работы",
      navExhibitions: "Выставки",
      heroEyebrow: "Художник · Москва",
      heroNameFirst: "Юра",
      heroNameLast: "Конышев",
      heroIntro: "Живопись о людях, городе и странных связях между ними.",
      viewWorks: "Смотреть работы",
      portraitCaption: "Портрет художника",
      aboutTitle: "Инженер по образованию,<br><em>художник по призванию.</em>",
      aboutText: "Юра Конышев живёт и работает в Москве. Он выпускник МАИ и художник из Чертанова — района, который становится героем и декорацией его живописи.",
      baseLabel: "Город",
      baseValue: "Москва",
      practiceLabel: "Практика",
      practiceValue: "Живопись",
      educationLabel: "Образование",
      educationValue: "МАИ",
      selectedWorks: "Избранные работы",
      worksTitle: "Живопись",
      worksCount: "работ",
      filterAll: "Все",
      filterPrivate: "В частных коллекциях",
      exhibitionsTitle: "Выставочная<br><em>хроника</em>",
      soloExhibition: "Персональная выставка",
      mgdTitle: "Московская городская Дума",
      mgdPlace: "Москва · 2025",
      openExhibition: "Открыть страницу выставки в Московской городской Думе",
      futureEyebrow: "Сайт растёт вместе с практикой",
      futureTitle: "Следующие<br><em>главы</em>",
      futureNews: "Новости и новые выставки",
      futurePress: "Публикации и пресса",
      futureCatalog: "Скачиваемый каталог работ",
      footerLine: "Юра Конышев · Москва",
      backTop: "Наверх",
      privateLabel: "Частная коллекция",
      openWork: "Открыть работу",
      pageTitle: "Юра Конышев — художник",
      metaDescription: "Юра Конышев — художник из Чертанова. Работы и выставки."
    },
    zh: {
      skip: "跳到正文",
      menu: "菜单",
      navLabel: "主导航",
      languageLabel: "语言选择",
      filterLabel: "作品筛选",
      close: "关闭",
      navAbout: "关于艺术家",
      navWorks: "作品",
      navExhibitions: "展览",
      heroEyebrow: "艺术家 · 莫斯科",
      heroNameFirst: "尤拉",
      heroNameLast: "科内舍夫",
      heroIntro: "关于人与城市，以及两者之间奇妙联系的绘画。",
      viewWorks: "浏览作品",
      portraitCaption: "艺术家肖像",
      aboutTitle: "工程师出身，<br><em>因热爱成为艺术家。</em>",
      aboutText: "尤拉·科内舍夫生活并工作于莫斯科。他毕业于莫斯科航空学院，也是一位来自切尔塔诺沃的艺术家——这片城区常常成为他绘画中的主角和舞台。",
      baseLabel: "城市",
      baseValue: "莫斯科",
      practiceLabel: "创作领域",
      practiceValue: "绘画",
      educationLabel: "教育",
      educationValue: "莫斯科航空学院",
      selectedWorks: "精选作品",
      worksTitle: "绘画",
      worksCount: "件作品",
      filterAll: "全部",
      filterPrivate: "私人收藏",
      exhibitionsTitle: "展览<br><em>纪事</em>",
      soloExhibition: "个展",
      mgdTitle: "莫斯科市杜马",
      mgdPlace: "莫斯科 · 2025",
      openExhibition: "打开莫斯科市杜马展览页面",
      futureEyebrow: "网站与创作一同成长",
      futureTitle: "未来<br><em>篇章</em>",
      futureNews: "新闻与新展览",
      futurePress: "出版物与媒体报道",
      futureCatalog: "可下载的作品图录",
      footerLine: "尤拉·科内舍夫 · 莫斯科",
      backTop: "返回顶部",
      privateLabel: "私人收藏",
      openWork: "打开作品",
      pageTitle: "尤拉·科内舍夫 — 艺术家",
      metaDescription: "尤拉·科内舍夫是来自切尔塔诺沃的艺术家。作品与展览。"
    },
    en: {
      skip: "Skip to content",
      menu: "Menu",
      navLabel: "Main navigation",
      languageLabel: "Choose language",
      filterLabel: "Filter artworks",
      close: "Close",
      navAbout: "About",
      navWorks: "Works",
      navExhibitions: "Exhibitions",
      heroEyebrow: "Artist · Moscow",
      heroNameFirst: "Yura",
      heroNameLast: "Konyshev",
      heroIntro: "Painting about people, the city, and the strange connections between them.",
      viewWorks: "View works",
      portraitCaption: "Portrait of the artist",
      aboutTitle: "An engineer by training,<br><em>an artist by calling.</em>",
      aboutText: "Yura Konyshev lives and works in Moscow. A graduate of the Moscow Aviation Institute, he is an artist from Chertanovo — a district that becomes both subject and setting in his paintings.",
      baseLabel: "Based in",
      baseValue: "Moscow",
      practiceLabel: "Practice",
      practiceValue: "Painting",
      educationLabel: "Education",
      educationValue: "Moscow Aviation Institute",
      selectedWorks: "Selected works",
      worksTitle: "Painting",
      worksCount: "works",
      filterAll: "All",
      filterPrivate: "Private collections",
      exhibitionsTitle: "Exhibition<br><em>chronicle</em>",
      soloExhibition: "Solo exhibition",
      mgdTitle: "Moscow City Duma",
      mgdPlace: "Moscow · 2025",
      openExhibition: "Open the Moscow City Duma exhibition page",
      futureEyebrow: "The website grows with the practice",
      futureTitle: "Next<br><em>chapters</em>",
      futureNews: "News and upcoming exhibitions",
      futurePress: "Publications and press",
      futureCatalog: "Downloadable catalogue of works",
      footerLine: "Yura Konyshev · Moscow",
      backTop: "Back to top",
      privateLabel: "Private collection",
      openWork: "Open artwork",
      pageTitle: "Yura Konyshev — Artist",
      metaDescription: "Yura Konyshev is an artist from Chertanovo. Works and exhibitions."
    },
    ar: {
      skip: "الانتقال إلى المحتوى",
      menu: "القائمة",
      navLabel: "التنقل الرئيسي",
      languageLabel: "اختيار اللغة",
      filterLabel: "تصفية الأعمال",
      close: "إغلاق",
      navAbout: "عن الفنان",
      navWorks: "الأعمال",
      navExhibitions: "المعارض",
      heroEyebrow: "فنان · موسكو",
      heroNameFirst: "يورا",
      heroNameLast: "كونيشيف",
      heroIntro: "لوحات عن الناس والمدينة والروابط الغريبة بينهما.",
      viewWorks: "مشاهدة الأعمال",
      portraitCaption: "صورة الفنان",
      aboutTitle: "مهندس بالتعليم،<br><em>وفنان بالشغف.</em>",
      aboutText: "يعيش يورا كونيشيف ويعمل في موسكو. تخرّج في معهد موسكو للطيران، وهو فنان من تشيرتانوفو — الحي الذي يتحول إلى بطل ومشهد في لوحاته.",
      baseLabel: "المدينة",
      baseValue: "موسكو",
      practiceLabel: "الممارسة",
      practiceValue: "الرسم",
      educationLabel: "التعليم",
      educationValue: "معهد موسكو للطيران",
      selectedWorks: "أعمال مختارة",
      worksTitle: "لوحات",
      worksCount: "عملاً",
      filterAll: "الكل",
      filterPrivate: "ضمن مجموعات خاصة",
      exhibitionsTitle: "سجل<br><em>المعارض</em>",
      soloExhibition: "معرض فردي",
      mgdTitle: "مجلس دوما مدينة موسكو",
      mgdPlace: "موسكو · 2025",
      openExhibition: "فتح صفحة المعرض في مجلس دوما مدينة موسكو",
      futureEyebrow: "ينمو الموقع مع الممارسة الفنية",
      futureTitle: "الفصول<br><em>القادمة</em>",
      futureNews: "الأخبار والمعارض الجديدة",
      futurePress: "المنشورات والتغطية الصحفية",
      futureCatalog: "كتالوج الأعمال القابل للتنزيل",
      footerLine: "يورا كونيشيف · موسكو",
      backTop: "إلى الأعلى",
      privateLabel: "مجموعة خاصة",
      openWork: "فتح العمل",
      pageTitle: "يورا كونيشيف — فنان",
      metaDescription: "يورا كونيشيف فنان من تشيرتانوفو. الأعمال والمعارض."
    }
  },

  artworks: [
    {
      id: "roma-logvin",
      image: "assets/artworks/01-roma-logvin.webp",
      status: "private",
      ru: { title: "Рома Логвин", meta: "Холст, масло · в частной коллекции" },
      zh: { title: "罗马·洛格温", meta: "布面油画 · 私人收藏" },
      en: { title: "Roma Logvin", meta: "Oil on canvas · private collection" },
      ar: { title: "روما لوغفين", meta: "زيت على قماش · مجموعة خاصة" }
    },
    {
      id: "rik",
      image: "assets/artworks/02-rik.webp",
      status: "catalog",
      ru: { title: "Административное здание в Чертаново. «РИК»", meta: "Холст, масло" },
      zh: { title: "切尔塔诺沃行政大楼“РИК”", meta: "布面油画" },
      en: { title: "Administrative Building in Chertanovo. ‘RIK’", meta: "Oil on canvas" },
      ar: { title: "المبنى الإداري في تشيرتانوفو «ريك»", meta: "زيت على قماش" }
    },
    {
      id: "old-chertanovo",
      image: "assets/artworks/03-old-chertanovo.webp",
      status: "private",
      ru: { title: "Старое Чертаново", meta: "Холст, масло · 60 × 80 см · в частной коллекции" },
      zh: { title: "老切尔塔诺沃", meta: "布面油画 · 60 × 80 厘米 · 私人收藏" },
      en: { title: "Old Chertanovo", meta: "Oil on canvas · 60 × 80 cm · private collection" },
      ar: { title: "تشيرتانوفو القديمة", meta: "زيت على قماش · 60 × 80 سم · مجموعة خاصة" }
    },
    {
      id: "swans",
      image: "assets/artworks/04-swans.webp",
      status: "private",
      ru: { title: "Лебеди", meta: "Холст, масло · 100 × 100 см · в частной коллекции" },
      zh: { title: "天鹅", meta: "布面油画 · 100 × 100 厘米 · 私人收藏" },
      en: { title: "Swans", meta: "Oil on canvas · 100 × 100 cm · private collection" },
      ar: { title: "البجع", meta: "زيت على قماش · 100 × 100 سم · مجموعة خاصة" }
    },
    {
      id: "municipal-machines",
      image: "assets/artworks/05-municipal-machines.webp",
      status: "private",
      ru: { title: "Московские коммунальные машины", meta: "Холст, масло · в частной коллекции" },
      zh: { title: "莫斯科市政车辆", meta: "布面油画 · 私人收藏" },
      en: { title: "Moscow Municipal Vehicles", meta: "Oil on canvas · private collection" },
      ar: { title: "مركبات الخدمات البلدية في موسكو", meta: "زيت على قماش · مجموعة خاصة" }
    },
    {
      id: "gagra",
      image: "assets/artworks/06-gagra.webp",
      status: "catalog",
      ru: { title: "Гагра", meta: "Холст, масло" },
      zh: { title: "加格拉", meta: "布面油画" },
      en: { title: "Gagra", meta: "Oil on canvas" },
      ar: { title: "غاغرا", meta: "زيت على قماش" }
    },
    {
      id: "creator",
      image: "assets/artworks/07-creator.webp",
      status: "private",
      ru: { title: "Творец и детище", meta: "Холст, масло · в частной коллекции" },
      zh: { title: "创作者与造物", meta: "布面油画 · 私人收藏" },
      en: { title: "The Creator and His Creation", meta: "Oil on canvas · private collection" },
      ar: { title: "المبدع وصنيعته", meta: "زيت على قماش · مجموعة خاصة" }
    },
    {
      id: "swans-ii",
      image: "assets/artworks/08-swans-ii.webp",
      status: "catalog",
      ru: { title: "Лебеди II", meta: "Холст, масло" },
      zh: { title: "天鹅 II", meta: "布面油画" },
      en: { title: "Swans II", meta: "Oil on canvas" },
      ar: { title: "البجع II", meta: "زيت على قماش" }
    },
    {
      id: "fish-port",
      image: "assets/artworks/09-fish-port.webp",
      status: "catalog",
      ru: { title: "Рыбный порт, балалайка и скрипка", meta: "Картон, масло" },
      zh: { title: "渔港、巴拉莱卡琴与小提琴", meta: "纸板油画" },
      en: { title: "Fishing Port, Balalaika and Violin", meta: "Oil on cardboard" },
      ar: { title: "ميناء الصيد والبالالايكا والكمان", meta: "زيت على كرتون" }
    },
    {
      id: "pasha",
      image: "assets/artworks/10-pasha.webp",
      status: "catalog",
      ru: { title: "Паша танкист", meta: "Холст на картоне, масло" },
      zh: { title: "坦克兵帕沙", meta: "纸板裱布油画" },
      en: { title: "Pasha the Tankman", meta: "Oil on canvas mounted on board" },
      ar: { title: "باشا، جندي الدبابات", meta: "زيت على قماش مثبت على كرتون" }
    },
    {
      id: "filyor",
      image: "assets/artworks/11-filyor.webp",
      status: "catalog",
      ru: { title: "Филёр", meta: "Холст на картоне, масло" },
      zh: { title: "密探", meta: "纸板裱布油画" },
      en: { title: "The Surveillance Agent", meta: "Oil on canvas mounted on board" },
      ar: { title: "المراقب السري", meta: "زيت على قماش مثبت على كرتون" }
    },
    {
      id: "portal",
      image: "assets/artworks/12-portal.webp",
      status: "catalog",
      ru: { title: "Портал", meta: "Холст, масло · 80 × 80 см" },
      zh: { title: "入口", meta: "布面油画 · 80 × 80 厘米" },
      en: { title: "Portal", meta: "Oil on canvas · 80 × 80 cm" },
      ar: { title: "البوابة", meta: "زيت على قماش · 80 × 80 سم" }
    },
    {
      id: "miroslava",
      image: "assets/artworks/13-miroslava.webp",
      status: "private",
      ru: { title: "Мирослава", meta: "Холст, масло · 50 × 65 см · в частной коллекции" },
      zh: { title: "米罗丝拉娃", meta: "布面油画 · 50 × 65 厘米 · 私人收藏" },
      en: { title: "Miroslava", meta: "Oil on canvas · 50 × 65 cm · private collection" },
      ar: { title: "ميروسلافا", meta: "زيت على قماش · 50 × 65 سم · مجموعة خاصة" }
    },
    {
      id: "night-hunt",
      image: "assets/artworks/14-night-hunt.webp",
      status: "catalog",
      ru: { title: "Ночная охота", meta: "Холст, масло" },
      zh: { title: "夜猎", meta: "布面油画" },
      en: { title: "Night Hunt", meta: "Oil on canvas" },
      ar: { title: "الصيد الليلي", meta: "زيت على قماش" }
    },
    {
      id: "woman",
      image: "assets/artworks/15-woman.webp",
      status: "private",
      ru: { title: "Женщина", meta: "Холст, масло · в частной коллекции" },
      zh: { title: "女人", meta: "布面油画 · 私人收藏" },
      en: { title: "Woman", meta: "Oil on canvas · private collection" },
      ar: { title: "امرأة", meta: "زيت على قماش · مجموعة خاصة" }
    },
    {
      id: "not-sisters",
      image: "assets/artworks/16-not-sisters.webp",
      status: "catalog",
      ru: { title: "Не сёстры", meta: "Холст, масло · 71 × 120 см" },
      zh: { title: "并非姐妹", meta: "布面油画 · 71 × 120 厘米" },
      en: { title: "Not Sisters", meta: "Oil on canvas · 71 × 120 cm" },
      ar: { title: "لسن أخوات", meta: "زيت على قماش · 71 × 120 سم" }
    }
  ]
};
